import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Sidebar } from './components/sidebar'
import { Footer } from './components/footer'
import { Header } from './components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <div className="grid grid-cols-[240px_minmax(0,1fr)]">
        <Sidebar />
        <div>
          <Header />
          {children}
        </div>
      </div>
      <Footer />
    </>
  )
}
